version: 2.1

orbs:
  docker: circleci/docker@0.0.12
  maven: circleci/maven@1.4.0

workflows:
  build-docker-image-only:
    jobs:
      - docker/publish:
          image: sagarikaB/user-blog-api-itest
          update-description: true
  maven_test:
    jobs:
      - maven/test:
        test_results_path: target/cucumber

